/* AUTOGENERATED by pargen 0.5.0
 * cmd: C:\Users\ldubies\Repos\flashcontainer\.venv\Scripts\pargen --ihex --csrc --gld --pyhexdump --destdir param --filename param param\structexample.xml
 * Time: 2023-08-30 15:40:22.608431
 * Buildkey: 3979c938-ebaa-4c7d-b8fc-5b0624f977ec
 * !! DO NOT EDIT MANUALLY !!
 */

#include "param.h"

/* BEGIN Block paraBlkSafety in container CodeFlash @ 0x81000000
 *
 * This block is used for any-safety related parameters.
 */
volatile const pargen_header_type_t paraBlkSafety_blkhdr =
{
    0x0D00,
    0x0001,
    0x0000,
    0x0000,
    0x00000000,
    0x00000200,
};

/* Parameter array @ 0x81000010
 */
volatile const float array[6] = 

{
      0.11100000,  -2.09999990,   3.20000005,   4.50000000, 
      5.40000010,   6.50000000
};

/* Parameter hello @ 0x81000100
 */
volatile const char hello[13] = 

{
    0x48, 0x65, 0x6C, 0x6C, 
    0x6F, 0x20, 0x77, 0x6F, 
    0x72, 0x6C, 0x64, 0x21, 
    0x00
};

/* Parameter val @ 0x8100010e
 */
volatile const uint16_t val = 
0x1604;

/* Parameter birthday @ 0x81000110
 */
volatile const float birthday = 
  0.16046900;

/* Parameter negativePi @ 0x81000114
 */
volatile const float negativePi = 
 -3.14100003;

/* Parameter crc2 @ 0x810001fc
 * block crc32 (IEEE802.3)
 * crc: 0x81000000-0x810001FB  polynomial:0x4C11DB7, 32 Bit, init:0xFFFFFFFF, reverse in:True, reverse out:True, final xor:True, access:8, swap:False
 */
volatile const uint32_t crc2 = 
0x330119E6;

/* END Block paraBlkSafety */

/* BEGIN Block structTestBlock in container CodeFlash @ 0x81000200
 *
 * This block contains parameters that use structs
 */
volatile const pargen_header_type_t structTestBlock_blkhdr =
{
    0x0E12,
    0x0001,
    0x0000,
    0x0000,
    0x00000000,
    0x00000200,
};

/* Parameter simpy @ 0x81000210
 */
volatile const pargen_SimpleS_type_t simpy = {
    0x03,
    0x05,
    0xD7,
};

/* Parameter biggy @ 0x81000213
 */
volatile const pargen_ComplexS_type_t biggy = {
    0x01,
    {0xFF, 0xFF, 0xFF, 0xFF},
    0x2F59,
    {0xFF, 0xFF},
    {0x0001, 0x0004, 0x0010, 0x0040},
};

/* END Block structTestBlock */

