/* AUTOGENERATED by pargen 0.5.0
 * cmd: C:\Users\ldubies\Repos\flashcontainer\.venv\Scripts\pargen --ihex --csrc --gld --pyhexdump --destdir param --filename param param\structexample.xml
 * Time: 2023-08-30 15:40:22.608431
 * Buildkey: 3979c938-ebaa-4c7d-b8fc-5b0624f977ec
 * !! DO NOT EDIT MANUALLY !!
 */

#ifndef PARGEN_HEADER_INCLUDED_PARAM
#define PARGEN_HEADER_INCLUDED_PARAM

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
typedef struct sruct_pargen_header_type
{
    uint16_t id;
    uint16_t major;
    uint16_t minor;
    uint16_t dataver;
    uint32_t reserved;
    uint32_t length;
} pargen_header_type_t;

/* Typedef for SimpleS struct *
 * This struct is super simple
 */
#pragma pack(push, 1)
typedef struct sruct_pargen_SimpleS_type
{
    uint8_t int1;
    uint8_t int2;
    uint8_t smallcrc;
} pargen_SimpleS_type_t;
#pragma pack(pop)

/* Typedef for ComplexS struct *
 * This struct will feature padding and arrays
 */
#pragma pack(push, 1)
typedef struct sruct_pargen_ComplexS_type
{
    uint8_t int1;
    char padding0[4];
    uint16_t int2;
    char padding1[2];
    uint16_t intarray[4];
} pargen_ComplexS_type_t;
#pragma pack(pop)

/* BEGIN Block paraBlkSafety in container CodeFlash @ 0x81000000
 *
 * This block is used for any-safety related parameters.
 */
extern volatile const pargen_header_type_t paraBlkSafety_blkhdr;

/* Parameter array @ 0x81000010
 */
extern volatile const float array[6];

/* Parameter hello @ 0x81000100
 */
extern volatile const char hello[13];

/* Parameter val @ 0x8100010e
 */
extern volatile const uint16_t val;

/* Parameter birthday @ 0x81000110
 */
extern volatile const float birthday;

/* Parameter negativePi @ 0x81000114
 */
extern volatile const float negativePi;

/* Parameter crc2 @ 0x810001fc
 * block crc32 (IEEE802.3)
 * crc: 0x81000000-0x810001FB  polynomial:0x4C11DB7, 32 Bit, init:0xFFFFFFFF, reverse in:True, reverse out:True, final xor:True, access:8, swap:False
 */
extern volatile const uint32_t crc2;

/* END Block paraBlkSafety */

/* BEGIN Block structTestBlock in container CodeFlash @ 0x81000200
 *
 * This block contains parameters that use structs
 */
extern volatile const pargen_header_type_t structTestBlock_blkhdr;

/* Parameter simpy @ 0x81000210
 */
extern volatile const pargen_SimpleS_type_t simpy;

/* Parameter biggy @ 0x81000213
 */
extern volatile const pargen_ComplexS_type_t biggy;

/* END Block structTestBlock */

#ifdef __cplusplus
}
#endif
#endif
