/* AUTOGENERATED by pargen 0.3.0
 * cmd: C:\projects\privat\flashcontainer\.venv\Scripts\pargen --ihex --csrc --gld --pyhexdump --destdir param param\param.xml
 * Time: 2023-03-20 08:26:08.781190
 * Buildkey: f1deb4e8-c0cb-40ac-a24e-9f790a4345fd
 * !! DO NOT EDIT MANUALLY !!
 */

#ifndef PARGEN_HEADER_INCLUDED_PARAM
#define PARGEN_HEADER_INCLUDED_PARAM

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
typedef struct sruct_pargen_header_type
{
    uint16_t id;
    uint16_t major;
    uint16_t minor;
    uint16_t dataver;
    uint32_t reserved;
    uint32_t length;
} pargen_header_type_t;

/* BEGIN Block par in container EEPROM @ 0x81000000
 *
 * 1Kb Example parameter block for displaying a flashable message with update delay
 */
extern volatile const pargen_header_type_t par_blkhdr;

/* Parameter par_UpdateDelay_ms @ 0x81000010
 * Interval time between dumping welcome message.
 */
extern volatile const uint16_t par_UpdateDelay_ms;

/* Parameter par_WelcomeMsg_str @ 0x81000012
 * Message to display in endless loop.
 */
extern volatile const char par_WelcomeMsg_str[49];

/* Parameter par_crc @ 0x810003fc
 * crc: 0x81000000-0x810003FB  polynomial:0x4C11DB7, 32 Bit, init:0xFFFFFFFF, reverse in:True, reverse out:True, final xor:True, access:1, swap:False
 */
extern volatile const uint32_t par_crc;

/* END Block par
 */

#ifdef __cplusplus
}
#endif
#endif
